solutions/2/Practice2/Practice2/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Practice2.Domain.Abstract;
using Practice2.Domain.Concrete;
using Practice2.Domain.Entities;

namespace Practice2.Controllers
{
    public class ActorController : Controller
    {
        private readonly IMovieRepository repo;

        int pageSize = 5;

        public ActorController(IMovieRepository movieRepo)
        {
            repo = movieRepo;
        }

        // GET: Actor
        public IActionResult Index(int? page, string searchText, bool? firstNameSort, bool? lastNameSort)
        {
            int _page = 1;
            if (page != null)
                _page = (int)page;

            // searching
            IQueryable<Actor> needActors;
            if (searchText == null || searchText.Equals(""))
            {
                needActors = repo.Actors;
            }
            else
            {
                var token = searchText.Trim().ToLower();

                needActors = repo.Actors.Where(actor =>
                actor.FirstName.ToLower().Contains(token)
               || actor.LastName.ToLower().Contains(token)
               || (actor.FirstName + " " + actor.LastName).ToLower().Contains(token)
               || (actor.LastName + " " + actor.FirstName).ToLower().Contains(token));
            }

            int actorsCount = needActors.Count();
            if (actorsCount == 0)
            {
                ViewBag.CurrentPage = 1;
                ViewBag.PagesCount = 1;
                ViewBag.SearchText = searchText;
                return View(new List<Actor>());
            }

            // sorting
            if (firstNameSort == null && lastNameSort == null)
                needActors = needActors.OrderBy(a => a.LastName);
            else
            {
                if (firstNameSort != null)
                {
                    if ((bool)firstNameSort)
                        needActors = needActors.OrderBy(a => a.FirstName);
                    if (!(bool)firstNameSort)
                        needActors = needActors.OrderByDescending(a => a.FirstName);
                    ViewBag.FirstNameSort = (bool)firstNameSort;
                }
                else if (lastNameSort != null)
                {
                    if ((bool)lastNameSort)
                        needActors = needActors.OrderBy(a => a.LastName);
                    if (!(bool)lastNameSort)
                        needActors = needActors.OrderByDescending(a => a.LastName);
                    ViewBag.LastNameSort = (bool)lastNameSort;
                }
            }

            // pagination
            int pagesCount = (int)Math.Ceiling((double)actorsCount / pageSize);
            if (_page > pagesCount || _page < 1)
                _page = 1;

            var actors = needActors
                    .Skip((_page - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();
            ViewBag.CurrentPage = _page;
            ViewBag.PagesCount = pagesCount;
            ViewBag.SearchText = searchText;

            return View(actors);
        }

        // GET: Actor/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();

            var actor = repo.Actors
                .Include(a => a.MovieActors)
                    .ThenInclude(ma => ma.Movie)
                .FirstOrDefault(a => a.Id == id);

            if (actor == null)
                return NotFound();

            return View(actor);
        }

        // GET: Actor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,FirstName,LastName")] Actor actor)
        {
            bool baseValid = ModelState.IsValid;
            bool actorNameValid = CheckActor(actor.FirstName, actor.LastName, actor.Id);
            if (!actorNameValid)
            {
                ModelState.AddModelError("", "This actor name already in use");
            }
            if (baseValid && actorNameValid)
            {
                actor.FirstName = actor.FirstName.Trim();
                actor.LastName = actor.LastName.Trim();
                int actorId = repo.Add(actor);
                return RedirectToAction(nameof(Details), new { id = actorId });
            }
            return View(actor);
        }

        // GET: Actor/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var actor = repo.FindActor((int)id);
            if (actor == null)
                return NotFound();

            return View(actor);
        }

        // POST: Actor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName")] Actor actor)
        {
            if (id != actor.Id)
                return NotFound();

            bool baseValid = ModelState.IsValid;
            bool actorNameValid = CheckActor(actor.FirstName, actor.LastName, actor.Id);
            if (!actorNameValid)
            {
                ModelState.AddModelError("", "This actor name already in use");
            }
            if (baseValid && actorNameValid)
            {
                actor.FirstName = actor.FirstName.Trim();
                actor.LastName = actor.LastName.Trim();

                // update foto
                var oldActor = repo.FindActor(actor.Id);
                string oldFileName = oldActor.FirstName + " " + oldActor.LastName;
                string newFileName = actor.FirstName + " " + actor.LastName;

                var curDir = Directory.GetCurrentDirectory();
                var oldImagePath = curDir + "/wwwroot" + $"/images/actors/{oldFileName}.jpg";
                var newImagePath = curDir + "/wwwroot" + $"/images/actors/{newFileName}.jpg";

                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Move(oldImagePath, newImagePath);
                }

                // update actor
                repo.Update(actor);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            return View(actor);
        }

        // GET: Actor/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var actor = repo.FindActor((int)id);
            if (actor == null)
                return NotFound();

            return View(actor);
        }

        // POST: Actor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var actor = repo.FindActor(id);
            repo.Remove(actor);
            return RedirectToAction(nameof(Index));
        }

        // GET: Actor/Search/5
        public IActionResult Search(string searchText)
        {
            return RedirectToAction(nameof(Index), new { page = 1, searchText = searchText });
        }

        // POST: Actor/AddFoto
        [HttpPost]
        public IActionResult AddFoto(int id, IFormFile uploadedFile)
        {
            if (uploadedFile == null)
            {
                return RedirectToAction(nameof(Edit), new { id = id });
            }

            var actor = repo.FindActor(id);
            string fileName = actor.FirstName + " " + actor.LastName;
            var relImagePath = $"/images/actors/{fileName}.jpg";
            var curDir = Directory.GetCurrentDirectory();
            var imagePath = curDir + "/wwwroot" + relImagePath;

            string userFileName = uploadedFile.FileName;
            var tokens = userFileName.Split(new char[] { '.' });
            var extension = tokens[tokens.Length - 1];
            
            if (extension.Equals("jpg") && uploadedFile.Length <= (1024*1024*2))
            {
                using (var fs = new FileStream(imagePath, FileMode.Create))
                {
                    uploadedFile.CopyTo(fs);
                }
            }

            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Actor/DeleteFoto
        [HttpGet]
        public IActionResult DeleteFoto(int id)
        {
            var actor = repo.FindActor(id);
            string fileName = actor.FirstName + " " + actor.LastName;
            var relImagePath = $"/images/actors/{fileName}.jpg";
            var curDir = Directory.GetCurrentDirectory();
            var imagePath = curDir + "/wwwroot" + relImagePath;

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            return RedirectToAction(nameof(Details), new { id = id });
        }

        public bool CheckActor(string firstName, string lastName, int id)
        {
            if (firstName == null || lastName == null 
                || firstName.Equals("") || lastName.Equals(""))
                return false;

solutions/2/Practice2/Practice2/Views/Movie/Create.cshtml
@model Practice2.Domain.Entities.Movie

@{
    //Layout = null;
    ViewData["Title"] = "Create movie";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h4>Movie</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" type="text" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Year" class="control-label"></label>
                    <input asp-for="Year" type="number" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" type="text" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" type="number" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Genre" class="control-label"></label>
                    <select asp-for="GenreId" class="form-control" asp-items="ViewBag.Genres"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

@*@section scripts{
    @Html.Partial("_ValidationScriptsPartial")
}*@

solutions/2/Practice2/Practice2/Views/Movie/Delete.cshtml
@model Practice2.Domain.Entities.Movie

@{
    //Layout = null;
    ViewData["Title"] = "Delete movie";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

solutions/2/Practice2/Practice2/Views/Movie/Details.cshtml
@model Practice2.Domain.Entities.Movie
@using System.IO

@{
    //Layout = null;
    ViewData["Title"] = "Movie details";

    var imagePath = $"/images/movies/{Model.Name}.jpg";
    var imagePathStub = $"/images/movies/no_signal.jpg";
    var curDir = Directory.GetCurrentDirectory();

    if (!File.Exists(curDir + "/wwwroot" + imagePath))
    {
        imagePath = imagePathStub;
    }

    var movieActors = Model.MovieActors;
    movieActors = movieActors.OrderBy(ma => ma.Actor.LastName).ToList();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Movie</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Year)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Rating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Genre.Name)
            </dd>
            <dt class="col-sm-2">
                Actors
            </dt>
            <dd class="col-sm-10">

                @foreach (var ma in movieActors)
                {
                    <a asp-action="Details" asp-controller="Actor" asp-route-id="@ma.Actor.Id">
                        @ma.Actor.FirstName @ma.Actor.LastName
                    </a>
                }

            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit movie</a> |
        <a asp-action="EditActors" asp-route-id="@Model.Id">Edit actors</a> |
        <a asp-action="Index">All movies</a>
    </div>
    <hr />
    <div>
        @{
            if (imagePath != "")
            {
                <img src="@imagePath" width="100%" />
            }
        }
    </div>
</body>
</html>

solutions/2/Practice2/Practice2/Views/Movie/Edit.cshtml
@model Practice2.Domain.Entities.Movie

@{
    //Layout = null;
    ViewData["Title"] = "Edit movie";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>Movie</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Year" class="control-label"></label>
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" type="text" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Genre" class="control-label"></label>
                    <select asp-for="GenreId" class="form-control" asp-items="ViewBag.Genres"></select>
                    <span asp-validation-for="GenreId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-outline-primary" />
                </div>
            </form>

            @* edit foto *@
            <form asp-action="AddFoto" method="post" enctype="multipart/form-data">
                <input type="hidden" name="id" value="@Model.Id" />
                <div class="form-group">
                    <label class="control-label">JPG foto, less than 5 MB</label>
                    <input type="file" name="uploadedFile" class="form-control-file" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload" class="btn btn-outline-primary" />
                </div>
            </form>
            <a class="btn btn-outline-primary" asp-action="DeleteFoto" asp-route-id="@Model.Id">
                Delete foto
            </a>
        </div>
    </div>
    <hr />
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a> |
        <a asp-action="Index">All movies</a>
    </div>

</body>
</html>

@*@section scripts{
    @Html.Partial("_ValidationScriptsPartial")
}*@

solutions/2/Practice2/Practice2/Views/Movie/EditActors.cshtml
@using Practice2.Domain.Entities

@{
    //Layout = null;
    ViewData["Title"] = "Edit movie";

    Movie movie = ViewBag.Movie;
    List<Actor> actors = ViewBag.Actors;
    List<Actor> newActors = ViewBag.NewActors;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <h4>Movie</h4>
    <hr />

    <dl class="row">
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @movie.Name
        </dd>
    </dl>
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <input name="movieId" type="hidden" value="@movie.Id" />
                <div class="form-group">
                    <label class="control-label">New actor</label>
                    <select name="actorId" class="form-control">
                        @foreach (var actor in newActors)
                        {
                            <option value="@actor.Id">@actor.FirstName @actor.LastName</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <table class="table">
        <tbody>
            @foreach (var actor in actors)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-controller="Actor" asp-route-Id="@actor.Id" style="text-decoration:none">
                            @actor.FirstName @actor.LastName
                        </a>
                    </td>
                    <td>
                        <a asp-action="EditActorRemove" asp-route-movieId="@movie.Id" asp-route-actorId="@actor.Id">Remove</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <hr />
    <div>
        <a asp-action="Details" asp-route-id="@movie.Id">@movie.Name</a> |
        <a asp-action="Index">All movies</a>
    </div>

</body>
</html>